Repository Nexters/tidify-iOS, pull requests merged in 2023-12, with the labels that each got.

#201 Feat: 홈&폴더 뷰에서 온보딩 연동
  Tidify/Targets/Tidify/Resources/Assets.xcassets/Folder/plusIcon.imageset/_Add.png
  Tidify/Targets/Tidify/Resources/Assets.xcassets/Folder/plusIcon.imageset/_Add@2x.png
  Tidify/Targets/Tidify/Resources/Assets.xcassets/Folder/plusIcon.imageset/_Add@3x.png
  Tidify/Targets/Tidify/Resources/Assets.xcassets/Onboarding/onboardingImage_0.imageset/onboardingImage_0.png
  Tidify/Targets/Tidify/Resources/Assets.xcassets/Onboarding/onboardingImage_0.imageset/onboardingImage_0@2x.png
  Tidify/Targets/Tidify/Resources/Assets.xcassets/Onboarding/onboardingImage_0.imageset/onboardingImage_0@3x.png
  Tidify/Targets/Tidify/Resources/Assets.xcassets/Onboarding/onboardingImage_1.imageset/onboardingImage_1.png
  Tidify/Targets/Tidify/Resources/Assets.xcassets/Onboarding/onboardingImage_1.imageset/onboardingImage_1@2x.png
  Tidify/Targets/Tidify/Resources/Assets.xcassets/Onboarding/onboardingImage_1.imageset/onboardingImage_1@3x.png
  Tidify/Targets/Tidify/Resources/Assets.xcassets/Onboarding/onboardingImage_2.imageset/onboardingImage_2.png
  Tidify/Targets/Tidify/Resources/Assets.xcassets/Onboarding/onboardingImage_2.imageset/onboardingImage_2@2x.png
  Tidify/Targets/Tidify/Resources/Assets.xcassets/Onboarding/onboardingImage_2.imageset/onboardingImage_2@3x.png
  Tidify/Targets/TidifyPresentation/Sources/Common/Base/Coordinator.swift
  Tidify/Targets/TidifyPresentation/Sources/Common/Base/MainCoordinator.swift
  Tidify/Targets/TidifyPresentation/Sources/Folder/FolderCoordinator.swift
  Tidify/Targets/TidifyPresentation/Sources/Folder/View/FolderViewController.swift
  Tidify/Targets/TidifyPresentation/Sources/Home/HomeCoordinator.swift
  Tidify/Targets/TidifyPresentation/Sources/Home/View/HomeViewController.swift
  Tidify/Targets/TidifyPresentation/Sources/Onboarding/OnboardingCoordinator.swift
  Tidify/Targets/TidifyPresentation/Sources/Onboarding/Reactor/OnboardingReactor.swift
  Tidify/Targets/TidifyPresentation/Sources/Onboarding/View/OnboardingViewController.swift
Labels: bug, refactoring, feature

#203 fix: 북마크 편집 화면에서 뷰를 탭 할 경우 키보드 내리도록 수정
  Tidify/Targets/TidifyPresentation/Sources/BookmarkCreation/View/BookmarkCreationViewController.swift
  Tidify/Targets/TidifyPresentation/Sources/Common/Base/Extension/Publisher+.swift
  Tidify/Targets/TidifyPresentation/Sources/Common/Base/View/TidifyTextFieldView.swift
  Tidify/Targets/TidifyPresentation/Sources/Folder/View/FolderCreationViewController.swift
  Tidify/Targets/TidifyPresentation/Sources/Folder/View/FolderDetailViewController.swift
  Tidify/Targets/TidifyPresentation/Sources/Folder/View/FolderViewController.swift
  Tidify/Targets/TidifyPresentation/Sources/Home/View/HomeViewController.swift
  Tidify/Targets/TidifyPresentation/Sources/Search/View/SearchViewController.swift
  Tidify/Targets/TidifyPresentation/Sources/Setting/VIew/SettingViewController.swift
  Tidify/Targets/TidifyPresentation/Sources/SignIn/View/LoginViewController.swift
  Tidify/Targets/TidifyPresentation/Sources/WebView/View/WebViewController.swift
Labels: bug

#202 feat: OpenGraph & Then 의존성 제거 및 OGImage 적용
  Tidify/Project.swift
  Tidify/Targets/TidifyData/Sources/Response/BookmarkDTO+Mapping.swift
  Tidify/Targets/TidifyDomain/Sources/Entities/Bookmark.swift
  Tidify/Targets/TidifyPresentation/Sources/Common/Base/SplashViewController.swift
  Tidify/Targets/TidifyPresentation/Sources/Common/Base/View/TidifyRightButtonTextField.swift
  Tidify/Targets/TidifyPresentation/Sources/Home/View/BookmarkCell.swift
  Tidify/Targets/TidifyPresentation/Sources/Onboarding/View/Cell/OnboardingCollectionViewCell.swift
  Tidify/Targets/TidifyPresentation/Sources/TabBar/View/TabBarController.swift
  Tidify/Tuist/Dependencies.swift
Labels: feature
