Repository Nexters/tidify-iOS, pull requests merged in 2023-04, with the labels that each got.

#170 Fix: 코디네이터 객체 resolve시 인터페이스에 의존하도록 수정
  Tidify/Targets/TidifyPresentation/Sources/Common/Base/MainCoordinator.swift
  Tidify/Targets/TidifyPresentation/Sources/Onboarding/OnboardingCoordinator.swift
  Tidify/Targets/TidifyPresentation/Sources/SignIn/SignInCoordinator.swift
  Tidify/Targets/TidifyPresentation/Sources/TabBar/TabBarCoordinator.swift
Labels: refactoring

#173 Refactor: 북마크 도메인 API 변경 대응
  Tidify/Targets/TidifyData/Sources/Repositories/DefaultBookmarkRepository.swift
  Tidify/Targets/TidifyData/Sources/Repositories/DefaultFolderRepository.swift
  Tidify/Targets/TidifyData/Sources/Repositories/DefaultSearchRepository.swift
  Tidify/Targets/TidifyData/Sources/Response/APIResponse.swift
  Tidify/Targets/TidifyData/Sources/Response/BookmarkDTO+Mapping.swift
  Tidify/Targets/TidifyData/Sources/Response/BookmarkListDTO+Mapping.swift
  Tidify/Targets/TidifyData/Sources/Response/DefaultResponse.swift
  Tidify/Targets/TidifyData/Sources/Response/FolderDTO+Mapping.swift
  Tidify/Targets/TidifyData/Sources/Response/FolderListDTO+Mapping.swift
  Tidify/Targets/TidifyData/Sources/Response/FolderUpdateResponse.swift
  Tidify/Targets/TidifyData/Sources/Response/Responsable.swift
  Tidify/Targets/TidifyData/Sources/Services/BookmarkService.swift
  Tidify/Targets/TidifyData/Sources/Services/FolderService.swift
  Tidify/Targets/TidifyDomain/Sources/Entities/Bookmark.swift
  Tidify/Targets/TidifyDomain/Sources/Interfaces/BookmarkRepository.swift
  Tidify/Targets/TidifyDomain/Sources/Interfaces/FolderRepository.swift
  Tidify/Targets/TidifyDomain/Sources/Interfaces/SearchRepository.swift
  Tidify/Targets/TidifyDomain/Sources/Requests/BookmarkListRequestDTO.swift
  Tidify/Targets/TidifyDomain/Sources/Requests/BookmarkRequestDTO.swift
  Tidify/Targets/TidifyDomain/Sources/Requests/FolderRequestDTO.swift
  Tidify/Targets/TidifyDomain/Sources/UseCases/BookmarkCreationUseCase.swift
  Tidify/Targets/TidifyDomain/Sources/UseCases/BookmarkUseCase.swift
  Tidify/Targets/TidifyDomain/Sources/UseCases/FolderUseCase.swift
  Tidify/Targets/TidifyDomain/Sources/UseCases/SearchUseCase.swift
  Tidify/Targets/TidifyDomain/Tests/Bookmark/MockBookmarkRepository.swift
  Tidify/Targets/TidifyDomain/Tests/Search/MockSearchRepository.swift
  Tidify/Targets/TidifyPresentation/Sources/BookmarkCreation/VIew/BookmarkCreationViewController.swift
  Tidify/Targets/TidifyPresentation/Sources/Common/Base/Extension/UIColor+.swift
  Tidify/Targets/TidifyPresentation/Sources/Common/Base/View/TidifyRightButtonTextField.swift
  Tidify/Targets/TidifyPresentation/Sources/Folder/Cell/FolderTableViewCell.swift
  Tidify/Targets/TidifyPresentation/Sources/Folder/Reactor/FolderDetailReactor.swift
  Tidify/Targets/TidifyPresentation/Sources/Folder/Reactor/FolderReactor.swift
  Tidify/Targets/TidifyPresentation/Sources/Folder/View/FolderCreationViewController.swift
  Tidify/Targets/TidifyPresentation/Sources/Folder/View/FolderViewController.swift
  Tidify/Targets/TidifyPresentation/Sources/Home/Reactor/HomeReactor.swift
  Tidify/Targets/TidifyPresentation/Sources/Home/View/BookmarkCell.swift
  Tidify/Targets/TidifyPresentation/Sources/Home/View/HomeViewController.swift
  Tidify/Targets/TidifyPresentation/Sources/Search/Reactor/SearchReactor.swift
  Tidify/Targets/TidifyPresentation/Tests/Home/HomeReactorTests.swift
Labels: refactoring

#172 Refactor: 폴더 관련 API 변경사항 반영
  Tidify/Targets/TidifyData/Sources/Repositories/DefaultFolderRepository.swift
  Tidify/Targets/TidifyData/Sources/Response/FolderCreationDTO+Mapping.swift
  Tidify/Targets/TidifyDomain/Sources/Interfaces/FolderRepository.swift
  Tidify/Targets/TidifyDomain/Sources/UseCases/FolderUseCase.swift
  Tidify/Targets/TidifyPresentation/Sources/Common/Base/Extension/UIColor+.swift
  Tidify/Targets/TidifyPresentation/Sources/Folder/FolderCoordinator.swift
  Tidify/Targets/TidifyPresentation/Sources/Folder/Reactor/FolderCreationReactor.swift
  Tidify/Targets/TidifyPresentation/Sources/Folder/Reactor/FolderReactor.swift
  Tidify/Targets/TidifyPresentation/Sources/Folder/View/FolderViewController.swift
  Tidify/Targets/TidifyPresentation/Sources/SignIn/Reactor/SignInReactor.swift
  Tidify/Targets/TidifyPresentation/Sources/SignIn/SignInCoordinator.swift
Labels: refactoring

#175 QA: 버그 수정 및 QA 반영
  Tidify/Targets/Tidify/Resources/Assets.xcassets/Onboarding/onboardingImage_3.imageset/onboardingImage_3.png
  Tidify/Targets/Tidify/Resources/Assets.xcassets/Onboarding/onboardingImage_3.imageset/onboardingImage_3@2x.png
  Tidify/Targets/Tidify/Resources/Assets.xcassets/Onboarding/onboardingImage_3.imageset/onboardingImage_3@3x.png
  Tidify/Targets/Tidify/Resources/Assets.xcassets/SignIn/login_apple_symbol.imageset/Contents.json
  Tidify/Targets/Tidify/Resources/Assets.xcassets/SignIn/login_apple_symbol.imageset/apple-16.png
  Tidify/Targets/Tidify/Resources/Assets.xcassets/SignIn/login_apple_symbol.imageset/apple-32.png
  Tidify/Targets/Tidify/Resources/Assets.xcassets/SignIn/login_apple_symbol.imageset/apple-48.png
  Tidify/Targets/TidifyData/Sources/Extension/Reactive+.swift
  Tidify/Targets/TidifyData/Sources/Response/BookmarkDTO+Mapping.swift
  Tidify/Targets/TidifyData/Sources/Services/BookmarkService.swift
  Tidify/Targets/TidifyDomain/Sources/Entities/Bookmark.swift
  Tidify/Targets/TidifyDomain/Sources/UseCases/BookmarkCreationUseCase.swift
  Tidify/Targets/TidifyPresentation/Sources/BookmarkCreation/Reactor/BookmarkCreationReactor.swift
  Tidify/Targets/TidifyPresentation/Sources/BookmarkCreation/VIew/BookmarkCreationViewController.swift
  Tidify/Targets/TidifyPresentation/Sources/Common/Base/View/TidifyRightButtonTextField.swift
  Tidify/Targets/TidifyPresentation/Sources/Common/BottomSheet/BottomSheetViewController.swift
  Tidify/Targets/TidifyPresentation/Sources/Common/BottomSheet/StickColorView.swift
  Tidify/Targets/TidifyPresentation/Sources/Folder/FolderCoordinator.swift
  Tidify/Targets/TidifyPresentation/Sources/Folder/Reactor/FolderCreationReactor.swift
  Tidify/Targets/TidifyPresentation/Sources/Folder/Reactor/FolderDetailReactor.swift
  Tidify/Targets/TidifyPresentation/Sources/Folder/Reactor/FolderReactor.swift
  Tidify/Targets/TidifyPresentation/Sources/Folder/View/FolderCreationViewController.swift
  Tidify/Targets/TidifyPresentation/Sources/Folder/View/FolderDetailViewController.swift
  Tidify/Targets/TidifyPresentation/Sources/Folder/View/FolderViewController.swift
  Tidify/Targets/TidifyPresentation/Sources/Home/Reactor/HomeReactor.swift
  Tidify/Targets/TidifyPresentation/Sources/Home/View/HomeViewController.swift
  Tidify/Targets/TidifyPresentation/Sources/Onboarding/Reactor/OnboardingReactor.swift
  Tidify/Targets/TidifyPresentation/Sources/Search/Reactor/SearchReactor.swift
  Tidify/Targets/TidifyPresentation/Sources/Search/View/SearchHeaderView.swift
  Tidify/Targets/TidifyPresentation/Sources/Search/View/SearchViewController.swift
  Tidify/Targets/TidifyPresentation/Sources/Setting/Reactor/SettingReactor.swift
  Tidify/Targets/TidifyPresentation/Sources/Setting/SettingCoordinator.swift
  Tidify/Targets/TidifyPresentation/Sources/Setting/VIew/Headers/SettingSectionHeaderView.swift
  Tidify/Targets/TidifyPresentation/Sources/Setting/VIew/SettingViewController.swift
  Tidify/Targets/TidifyPresentation/Sources/SignIn/Reactor/SignInReactor.swift
  Tidify/Targets/TidifyPresentation/Sources/SignIn/SignInCoordinator.swift
  Tidify/Targets/TidifyPresentation/Sources/SignIn/View/AuthViewController.swift
  Tidify/Targets/TidifyPresentation/Sources/SignIn/View/SignInViewController.swift
Labels: bug, feature

#177 Feat: 폴더 상세 뷰 API 연동 및 버그 수정
  Tidify/Targets/TidifyData/Sources/DataAssembly.swift
  Tidify/Targets/TidifyData/Sources/Repositories/DefaultFolderDetailRepository.swift
  Tidify/Targets/TidifyData/Sources/Services/FolderService.swift
  Tidify/Targets/TidifyDomain/Sources/DomainAssembly.swift
  Tidify/Targets/TidifyDomain/Sources/Interfaces/FolderDetailRepository.swift
  Tidify/Targets/TidifyDomain/Sources/UseCases/BookmarkUseCase.swift
  Tidify/Targets/TidifyDomain/Sources/UseCases/FolderDetailUseCase.swift
  Tidify/Targets/TidifyPresentation/Sources/Common/Base/View/TidifyTableView.swift
  Tidify/Targets/TidifyPresentation/Sources/DetailWebView/DetailWebCoordinator.swift
  Tidify/Targets/TidifyPresentation/Sources/Folder/FolderCoordinator.swift
  Tidify/Targets/TidifyPresentation/Sources/Folder/Reactor/FolderDetailReactor.swift
  Tidify/Targets/TidifyPresentation/Sources/Folder/View/FolderDetailViewController.swift
Labels: bug, feature

#181 Fix: 검색 뷰 버그 수정
  Tidify/Targets/TidifyData/Sources/Repositories/DefaultSearchRepository.swift
  Tidify/Targets/TidifyData/Sources/Services/BookmarkService.swift
  Tidify/Targets/TidifyPresentation/Sources/Home/View/BookmarkCell.swift
  Tidify/Targets/TidifyPresentation/Sources/Search/Reactor/SearchReactor.swift
  Tidify/Targets/TidifyPresentation/Sources/Search/View/SearchViewController.swift
Labels: bug
